### PR TITLE
21 python terminal

### PR DESCRIPTION
**Pull request by tomseli**
Created a simple terminal program. Requesting a review:

Features:
- Opening and closing automatically detected ports.
- Transmitting and receiving from a connected port.

Known bugs:
- Input buffer sometimes does not properly flush, causing messages to appear from the last connection on connection.

Notes: 
- The baudrate is currently locked to 115200.
- Two debug (sub)windows open on start up, these can safely be closed. At a later stage these can be moved to the menu bar or removed.

**Questions for both of you:** 
Are there any other features you would like to see at this stage?
Other than the denoted bug, can you find any others?

@JesseSwildens please test the Serial functionality on MacOS?

Arduino/PlatformIO code you can use to test. It simply echos a response and spams the terminal with timestamps. 

```c
#include <Arduino.h>

uint32_t last = 0;

void setup()
{
    Serial.begin(115200);
    delay(100);
}


void loop()
{
    if(Serial.available() > 0)
    {
        String data;
        data = Serial.readStringUntil('\n');
        
        Serial.println(data);
    }

    if((millis() - last) > 100)
    {
        Serial.println(millis());
        last = millis();
    }
}
```

### CODE REVIEW

**Comment by tomseli** [comment]
It's a draft :)

**Comment by tomseli** [comment]
@JesseSwildens adjusted port.name to port.device. Haven't got a clue how the layout would look on Linux, but at least it should work.

**Comment by tomseli** [comment]
> Resizing and initial launch are still not fully realized as it is still bit buggy.
> 
> Screenshot_2024-05-09_19-00-48
> 
> Screenshot_2024-05-09_19-09-07

For my idea: That first image has the buttons all in scrambled locations. Was that directly after start up? I can't seem te replicated that.

The second one was indeed a bug. Fixed now.

**Comment by tomseli** [comment]
> Maybe a suggestion that I won't really know if easy to implement. But would it be possible that when connecting to a device you'd clear the strings already present on screen so you start from an empty terminal every time you connect?

Done.

**Comment by tomseli** [comment]
Features:
- Opening and closing automatically detected ports.*
- Transmitting and receiving from a connected port.
- Single line coloring
- Debug tools

Known bugs:
- Input buffer sometimes does not properly flush, causing messages to appear from the last connection on connection.
- Program sometimes hangs after window resize. Seems to be an issue with the framework as the demo program has this issue too.

* Only detects port on start up

**Review by Mirkoet — APPROVED** [review]
works great, cant see anything in the code 👍

**Pull request merged**
